dataSourse:
  driverClassName: org.h2.Driver
  dbCreate: update
  username: root
  password: '1234'

enviroment:
  development:
    dataSourse:
      driverClassName: com.mysql.jdbc.Driver
      dbCreate: update
      url: jdbc:mysql://localhost/ordenaris
      username: root
      password: '1234'